language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dalmvicky/docker-react -f Dockerfile-dev .

script:
  - docker run -e CI=true dalmvicky/docker-react npm run test